libgcc: Exclude crtfastmath from nofpu build
Was already excluded on arm64 and mips.
Caused the following build error on x86:
  > error: implicit declaration of function '__builtin_ia32_ldmxcsr'

See ticket #CD-1227.

Change-Id: I9a5b78eef49ef6111adb9f9288c53786ae2b4c9b