same exception specification in declaration and implementation
The declaration and implementation of a function need to have the same
exception specification, otherwise newer Clang versions defaulting to
C++17 fail like

  uclibc/lib/libpthread/src/l4.cc:164:5: error:
    'pthread_setaffinity_np' is missing exception specification
    'throw()'

See ticket #CD-999.

Change-Id: I3cf2b974ca1c1b3ab8381b344ee204d056de1c2a