terminate_handler-l4: fix ancient gcc build error
gcc-4.9 was complaining with the following error:

  error: deducing from brace-enclosed initializer list requires
         #include <initializer_list>

Hence, add the missing header.
Also add a newline for cosmetic reasons.

Change-Id: I211c5ce7b0b7fbd17b99b541abd4d444c0cbe2d3