uclibc/linuxthreads: fix compile error for non-MMU
Otherwise you get following linking error, because
of missing functions in libc.a:
undefined reference to `__libc_enable_asynccancel'

Fix by Thorsten Glaser while hacking session.

Change-Id: I4c1b0d6e5fb9b8ea5a5b5b99d7f2bb2a229e52bb